### ISSUE TITLE
Info Lookup via bot

### ISSUE THREAD

**Issue by Jivaii** [ddavaham/dsrauth-issues#17]
Link item info via a bot command

Ships: Description, Traits, CPU, PG, Drone Bay, Drone bandwidth, High/Mid/Low slots, turret/missile hardpoints (Quick look up for fitting ideas)

Modules: Description, CPU, PG, Activation time/Duration, Optimal Range, Falloff Range, Boost amount (armour, shield, or other, like speed %)

**Comment by ddavaham** [comment]
Marking as a Dup of https://github.com/ddavaham/dsrauth-issues/issues/16
