### ISSUE TITLE
[FEATURE REQUEST] Role Control From Disco

### ISSUE THREAD

**Issue by Jadecca** [ddavaham/dsrauth-issues#22]
Dear WebDude,

Plz maek it so roles on the site can be controlled by what roles a pilot has in discord. i.e. set as having "Operations" role in disco would mean a certain level of access to admin part of site. Leik FC and JrFC - they'd see different doctrines, or say "Rookie" and "Member" would have different levels of access to doctrines.

**Comment by ddavaham** [comment]
This has been coded already and is another branch of the repo. It will be turned on by the end of the weekend

You will be able to access from the Servic Associations under each role.

![chrome_2018-01-26_22-36-21](https://user-images.githubusercontent.com/7141998/35468314-786b164e-02e9-11e8-88b3-955431741370.png)

**Comment by ddavaham** [comment]
There will be no control of roles from Discord to the Auth. The Auth was/will be designed to control Discord Roles. The Auth is meant to be a centralize point of control
